defaults:
  - _self_
  - callbacks: default.yaml

optimizer:
  name: Adam
  lr: 0.0001

scheduler:
  name: ReduceLROnPlateau
  mode: min
  factor: 0.1
  patience: 3
  min_lr: 0.1

batch_size: 512
num_epochs: 15
