model_path: dvc_store/experiments/humpback_whole_resnet/best.onnx

unique_labels: dvc_store/data/labels.json
unknown_label: new_whale

num_predictions: 5

image_size: 224
transforms:
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]
