checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ""
  filename: "best-{epoch}-{val_map:.2f}"
  monitor: val_map
  mode: max
  save_top_k: 1
  save_last: true
  every_n_epochs: 1

device_stats_monitor:
  _target_: pytorch_lightning.callbacks.DeviceStatsMonitor
